'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class book
    Public Property book_ID As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property subject_code As String
    <Required(ErrorMessage:="กรุณากรอก ชื่อเล่ม !")>
    <Display(Name:="ชื่อเล่ม")>
    Public Property Name_book As String
    <Required(ErrorMessage:="กรุณากรอก ประเภท !")>
    <Display(Name:="ประเภท")>
    Public Property type_book As String
    <Required(ErrorMessage:="กรุณากรอก วันที่สร้าง !")>
    <Display(Name:="วันที่สร้าง")>
    <DataType(DataType.Date)>
    Public Property Date_Start_Book As Date
    <Required(ErrorMessage:="กรุณากรอก ผู้สร้าง !")>
    <Display(Name:="ผู้สร้าง")>
    Public Property Creator As String
    <Required(ErrorMessage:="กรุณาเพิ่มไฟล์ !")>
    <Display(Name:="ไฟล์")>
    Public Property FilePath As String

    Public Overridable Property EssayTest As ICollection(Of EssayTest) = New HashSet(Of EssayTest)
    Public Overridable Property MultipleChoices As ICollection(Of MultipleChoices) = New HashSet(Of MultipleChoices)
    Public Overridable Property Position_Exam As ICollection(Of Position_Exam) = New HashSet(Of Position_Exam)
    Public Overridable Property ScoreUser As ICollection(Of ScoreUser) = New HashSet(Of ScoreUser)
    Public Overridable Property TrueFalse As ICollection(Of TrueFalse) = New HashSet(Of TrueFalse)

End Class
