'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class BranchTable
    Public Property Branch_id As Integer
    <Required(ErrorMessage:="กรุณากรอก สาขา/ฝ่าย !")>
    <Display(Name:="สาขา/ฝ่าย")>
    Public Property Branch_Title As String
    <Required(ErrorMessage:="กรุณากรอก ตำแหน่ง !")>
    <Display(Name:="ตำแหน่ง")>
    Public Property Position_id As Integer
    Public Overridable Property PositionTable As PositionTable
    Public Overridable Property EmployeeInformation As ICollection(Of EmployeeInformation) = New HashSet(Of EmployeeInformation)

End Class
