'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class EssayTest
    Public Property EssayTest_id As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property book_ID As Integer
    <Required(ErrorMessage:="กรุณากรอก คำถาม !")>
    <Display(Name:="คำถาม")>
    Public Property EssayTest_Question As String
    <Required(ErrorMessage:="กรุณากรอก คำตอบ User !")>
    <Display(Name:="คำตอบ User")>
    Public Property EssayTest_Answer_User As String
    <Required(ErrorMessage:="กรุณากรอก คำตอบ !")>
    <Display(Name:="คำตอบ")>
    Public Property EssayTest_Answer As String
    <Required(ErrorMessage:="กรุณากรอก วันที่สร้าง !")>
    <Display(Name:="วันที่สร้าง")>
    <DataType(DataType.Date)>
    Public Property EssayTest_ExamDate As Date

    Public Overridable Property book As book

End Class
