'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class MultipleChoices
    Public Property MultipleChoices_id As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property book_ID As Integer
    <Required(ErrorMessage:="กรุณากรอก คำถาม !")>
    <Display(Name:="คำถาม")>
    Public Property MultipleChoices_Question As String
    <Required(ErrorMessage:="กรุณากรอก ทางเลือก 1 !")>
    <Display(Name:="ทางเลือก 1 ")>
    Public Property Multiple_Choice1 As String
    <Required(ErrorMessage:="กรุณากรอก ทางเลือก 2 !")>
    <Display(Name:="ทางเลือก 2")>
    Public Property Multiple_Choice2 As String
    <Required(ErrorMessage:="กรุณากรอก ทางเลือก 3 !")>
    <Display(Name:="ทางเลือก 3")>
    Public Property Multiple_Choice3 As String
    <Required(ErrorMessage:="กรุณากรอก ทางเลือก 4 !")>
    <Display(Name:="ทางเลือก 4")>
    Public Property Multiple_Choice4 As String
    <Required(ErrorMessage:="กรุณากรอก คำตอบ !")>
    <Display(Name:="คำตอบ")>
    Public Property Multiple_Answer As String
    <Required(ErrorMessage:="กรุณากรอก วันที่สร้าง !")>
    <Display(Name:="วันที่สร้าง")>
    <DataType(DataType.Date)>
    Public Property Multiple_ExamDate As Date
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property subject_code As String

    Public Overridable Property book As book

End Class
