'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class News
    Public Property news_id As Integer
    <Required(ErrorMessage:="กรุณากรอก หัวข้อข่าว !")>
    <Display(Name:="หัวข้อข่าว")>
    Public Property news_title As String
    <Required(ErrorMessage:="กรุณากรอก เนื้อหาข่าว !")>
    <Display(Name:="เนื้อหาข่าว")>
    Public Property news_full_content As String
    <Required(ErrorMessage:="กรุณากรอก รหัสพนักงาน !")>
    <Display(Name:="รหัสพนักงาน")>
    Public Property emp_id As Integer
    <Required(ErrorMessage:="กรุณากรอก วันที่ประกาศ !")>
    <Display(Name:="วันที่ประกาศ")>
    <DataType(DataType.Date)>
    Public Property date_news_published As Date

    Public Overridable Property EmployeeInformation As EmployeeInformation

End Class
