'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class PositionTable
    Public Property Position_id As Integer
    <Required(ErrorMessage:="กรุณากรอก ตำแหน่ง !")>
    <Display(Name:="ตำแหน่ง")>
    Public Property Position_Title As String

    Public Overridable Property BranchTable As ICollection(Of BranchTable) = New HashSet(Of BranchTable)
    Public Overridable Property EmployeeInformation As ICollection(Of EmployeeInformation) = New HashSet(Of EmployeeInformation)

End Class
