'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Position_Exam
    Public Property exam_id As Integer
    <Required(ErrorMessage:="กรุณากรอก ตำแหน่ง !")>
    <Display(Name:="ตำแหน่ง")>
    Public Property Position_exam1 As String
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property book_ID As Nullable(Of Integer)

    Public Overridable Property book As book

End Class
