'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class QuizLomprayahEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=QuizLomprayahEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property book() As DbSet(Of book)
    Public Overridable Property BranchTable() As DbSet(Of BranchTable)
    Public Overridable Property EmployeeInformation() As DbSet(Of EmployeeInformation)
    Public Overridable Property EssayTest() As DbSet(Of EssayTest)
    Public Overridable Property MultipleChoices() As DbSet(Of MultipleChoices)
    Public Overridable Property News() As DbSet(Of News)
    Public Overridable Property Position_Exam() As DbSet(Of Position_Exam)
    Public Overridable Property PositionTable() As DbSet(Of PositionTable)
    Public Overridable Property ScoreUser() As DbSet(Of ScoreUser)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TrueFalse() As DbSet(Of TrueFalse)

End Class
