'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class ScoreUser
    Public Property score_id As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสพนักงาน !")>
    <Display(Name:="รหัสพนักงาน")>
    Public Property emp_id As Integer
    <Required(ErrorMessage:="กรุณากรอก คำถาม !")>
    <Display(Name:="คำถาม")>
    Public Property book_ID As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property Score As String
    <Required(ErrorMessage:="กรุณากรอก คะแนน !")>
    <Display(Name:="คะแนน")>
    Public Property Status As String
    <Required(ErrorMessage:="กรุณากรอก ครั้งที่สอบ !")>
    <Display(Name:="ครั้งที่สอบ")>
    Public Property Round As String
    <Required(ErrorMessage:="กรุณากรอก วันที่สอบ !")>
    <Display(Name:="วันที่สอบ")>
    <DataType(DataType.Date)>
    Public Property Scor_Date_Exam As Date

    Public Overridable Property book As book
    Public Overridable Property EmployeeInformation As EmployeeInformation

End Class
