'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class TrueFalse
    Public Property TrueFalse_id As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property book_ID As Integer
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property TrueFalse_Question As String
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property TrueFalse_Choice1 As String
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property TrueFalse_Choice As String
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property TrueFalse_Answer As String
    <Required(ErrorMessage:="กรุณากรอก รหัสเล่ม !")>
    <Display(Name:="รหัสเล่ม")>
    Public Property TrueFalse_ExamDate As Date

    Public Overridable Property book As book

End Class
